# Generated by Django 6.0.2 on 2026-02-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
            ],
            options={
                'db_table': 'trains',
                'indexes': [models.Index(fields=['source', 'destination'], name='trains_source_1e5fa5_idx')],
            },
        ),
    ]
